//! Generated by `codegen/create_gen_bif.py`
//! Creates a lookup table of BIF functions
//! Config used: OTP20 
#![allow(dead_code)]

use rt_defs::Arity;
use emulator::gen_atoms;
use term::lterm::*;
use bif;


pub struct BifTabItem {
    pub m: LTerm, 
    pub f: LTerm, 
    pub arity: Arity, 
    pub func: bif::BifFn
}


pub static BIF_TABLE: &'static [BifTabItem] = &[

    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::SYM_PLUS, arity: 2,
        func: bif::ubif_splus_2_2 },
    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::SYM_MINUS, arity: 2,
        func: bif::ubif_sminus_2_2 },
    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::SEQ_2, arity: 2,
        func: bif::ubif_seq_2_2 },
    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::SYM_EQ_EQ, arity: 2,
        func: bif::ubif_seqeq_2_2 },
    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::LENGTH, arity: 1,
        func: bif::gcbif_length_1 },
    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::SELF, arity: 0,
        func: bif::ubif_self_0 },
];

