//! Generated by `codegen/create_gen_bif.py`
//! Creates a lookup table of BIF functions
//! Config used: OTP20 
#![allow(dead_code)]

use crate::defs::Arity;
use crate::emulator::gen_atoms;
use crate::term::lterm::*;
use crate::bif;


pub struct BifTabItem {
    pub m: LTerm, 
    pub f: LTerm, 
    pub arity: Arity, 
    pub func: bif::BifFn
}


pub static BIF_TABLE: &'static [BifTabItem] = &[

    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::STIMES_2, arity: 2,
        func: bif::ubif_erlang_stimes_2_2 },
    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::SYM_PLUS, arity: 2,
        func: bif::ubif_erlang_splus_2_2 },
    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::EBIF_PLUSPLUS_2, arity: 2,
        func: bif::bif_erlang_ebif_plusplus_2_2 },
    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::SYM_MINUS, arity: 2,
        func: bif::ubif_erlang_sminus_2_2 },
    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::SNEQEQ_2, arity: 2,
        func: bif::ubif_erlang_sneqeq_2_2 },
    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::SLT_2, arity: 2,
        func: bif::ubif_erlang_slt_2_2 },
    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::SNEQ_2, arity: 2,
        func: bif::ubif_erlang_sneq_2_2 },
    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::SEQ_2, arity: 2,
        func: bif::ubif_erlang_seq_2_2 },
    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::SLE_2, arity: 2,
        func: bif::ubif_erlang_sle_2_2 },
    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::SYM_EQ_EQ, arity: 2,
        func: bif::ubif_erlang_seqeq_2_2 },
    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::SGT_2, arity: 2,
        func: bif::ubif_erlang_sgt_2_2 },
    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::SGE_2, arity: 2,
        func: bif::ubif_erlang_sge_2_2 },
    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::HD, arity: 1,
        func: bif::ubif_erlang_hd_1 },
    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::IS_PROCESS_ALIVE, arity: 1,
        func: bif::bif_erlang_is_process_alive_1 },
    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::LENGTH, arity: 1,
        func: bif::gcbif_erlang_length_1 },
    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::MAKE_FUN, arity: 3,
        func: bif::bif_erlang_make_fun_3 },
    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::NIF_ERROR, arity: 1,
        func: bif::bif_erlang_nif_error_1 },
    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::NIF_ERROR, arity: 2,
        func: bif::bif_erlang_nif_error_2 },
    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::SELF, arity: 0,
        func: bif::ubif_erlang_self_0 },
    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::SPAWN, arity: 3,
        func: bif::bif_erlang_spawn_3 },
    BifTabItem { m: gen_atoms::ERLANG, f: gen_atoms::TL, arity: 1,
        func: bif::ubif_erlang_tl_1 },
];

