//! Generated by `codegen/create_gen_bif.py`
//! Creates a lookup table of BIF functions
//! Config used: OTP21 
#![allow(dead_code)]

use crate::{native_fun, defs::Arity, term::lterm::*};

pub struct BifTabItem {
    pub m: LTerm, 
    pub f: LTerm, 
    pub arity: Arity, 
    pub func: native_fun::NativeFn
}


pub static BIF_TABLE: &'static [BifTabItem] = &[

];

