//! Generated by `codegen/create_gen_bif.py`
//! Creates a lookup table of BIF functions
//! Config used: OTP21
#![allow(dead_code)]

use crate::{defs::Arity, emulator::gen_atoms, native_fun, term::lterm::*};

pub struct BifTabItem {
  pub m: LTerm,
  pub f: LTerm,
  pub arity: Arity,
  pub func: native_fun::NativeFn,
}


pub static BIF_TABLE: &'static [BifTabItem] = &[
  BifTabItem {
    m: gen_atoms::LISTS,
    f: gen_atoms::MEMBER,
    arity: 2,
    func: native_fun::bif_lists_member_2,
  },
  BifTabItem {
    m: gen_atoms::ERTS_INTERNAL,
    f: gen_atoms::SPAWN_SYSTEM_PROCESS,
    arity: 3,
    func: native_fun::bif_erts_internal_spawn_system_process_3,
  },
];
