//! Generated by `codegen/create_gen_bif.py`
//! Creates a lookup table of BIF functions
//! Config used: OTP22 
#![allow(dead_code)]

use crate::{native_fun, defs::Arity, term::value::*};

pub struct BifTabItem {
    pub m: Term, 
    pub f: Term, 
    pub arity: Arity, 
    pub func: native_fun::NativeFn
}


pub static BIF_TABLE: &'static [BifTabItem] = &[

];

