//! Generated by codegen/create_vm_dispatch.py
//! Dispatch for all opcode types.
//! Config used: OTP20 
#![allow(dead_code)]

use beam::gen_op::OPCODE;
use emulator::runtime_ctx::Context;
use defs::Word;


#[inline(always)]
pub fn dispatch_op_inline(op: OPCODE, ctx: &mut Context) {
  match op {

    other => panic!("vm_dispatch: Opcode {:?} not implemented", other),   
  }
}

