//! Generated by codegen/create_gen_bif.py
//! Creates a lookup table of BIF functions
//! Config used: OTP20 
#![allow(dead_code)]

use defs::Arity;
use emulator::funarity::FunArity;
use emulator::gen_atoms;
use term::immediate;
use term::lterm::LTerm;
use bif;


type BifTabItem = (LTerm, LTerm, Arity, bif::BifFn);

pub static BIF_TABLE: &'static [BifTabItem] = &[

    (gen_atoms::ERLANG, gen_atoms::SELF, 0, bif::ubif_self_0),
];

