//! Generated by codegen/create_gen_bif.py
//! Creates a lookup table of BIF functions
//! Config used: OTP20 
#![allow(dead_code)]

use defs::{Arity, BifFn};
use emulator::funarity::FunArity;
use emulator::gen_atoms;
use term::immediate;
use term::lterm::LTerm;


pub static BIF_TABLE: &'static [(LTerm, LTerm, Arity, BifFn)] = &[

    (gen_atoms::ERLANG, gen_atoms::SELF, 0, ubif_self_0),
];

