//! Generated by `codegen/create_gen_atoms.py`
//! Creates array of predefined atoms
//! Config used: OTP20
#![allow(dead_code)]

use crate::term::lterm::*;


pub const MULTIPLY: LTerm = LTerm::make_atom(0);
pub const SYM_PLUS: LTerm = LTerm::make_atom(1);
pub const PLUSPLUS: LTerm = LTerm::make_atom(2);
pub const SYM_MINUS: LTerm = LTerm::make_atom(3);
pub const NOTEQUAL: LTerm = LTerm::make_atom(4);
pub const LESSTHAN: LTerm = LTerm::make_atom(5);
pub const NOTEQUAL_EXACT: LTerm = LTerm::make_atom(6);
pub const EQUAL_EXACT: LTerm = LTerm::make_atom(7);
pub const LESSEQUAL: LTerm = LTerm::make_atom(8);
pub const SYM_EQ_EQ: LTerm = LTerm::make_atom(9);
pub const GREATERTHAN: LTerm = LTerm::make_atom(10);
pub const GREATEREQUAL: LTerm = LTerm::make_atom(11);
pub const APPLY: LTerm = LTerm::make_atom(12);
pub const ATOM_TO_LIST: LTerm = LTerm::make_atom(13);
pub const BADARG: LTerm = LTerm::make_atom(14);
pub const BADARITH: LTerm = LTerm::make_atom(15);
pub const BADARITY: LTerm = LTerm::make_atom(16);
pub const BADFUN: LTerm = LTerm::make_atom(17);
pub const BADMATCH: LTerm = LTerm::make_atom(18);
pub const CASE_CLAUSE: LTerm = LTerm::make_atom(19);
pub const ERLANG: LTerm = LTerm::make_atom(20);
pub const ERROR: LTerm = LTerm::make_atom(21);
pub const EXIT: LTerm = LTerm::make_atom(22);
pub const FALSE: LTerm = LTerm::make_atom(23);
pub const FUNCTION_CLAUSE: LTerm = LTerm::make_atom(24);
pub const HD: LTerm = LTerm::make_atom(25);
pub const HIGH: LTerm = LTerm::make_atom(26);
pub const IF_CLAUSE: LTerm = LTerm::make_atom(27);
pub const INIT: LTerm = LTerm::make_atom(28);
pub const INTEGER_TO_LIST: LTerm = LTerm::make_atom(29);
pub const IS_PROCESS_ALIVE: LTerm = LTerm::make_atom(30);
pub const KILL: LTerm = LTerm::make_atom(31);
pub const KILLED: LTerm = LTerm::make_atom(32);
pub const LENGTH: LTerm = LTerm::make_atom(33);
pub const LISTS: LTerm = LTerm::make_atom(34);
pub const LOW: LTerm = LTerm::make_atom(35);
pub const MAKE_FUN: LTerm = LTerm::make_atom(36);
pub const MEMBER: LTerm = LTerm::make_atom(37);
pub const NIF_ERROR: LTerm = LTerm::make_atom(38);
pub const NOCATCH: LTerm = LTerm::make_atom(39);
pub const NORMAL: LTerm = LTerm::make_atom(40);
pub const OK: LTerm = LTerm::make_atom(41);
pub const SELF: LTerm = LTerm::make_atom(42);
pub const SPAWN: LTerm = LTerm::make_atom(43);
pub const SYSTEM_LIMIT: LTerm = LTerm::make_atom(44);
pub const THROW: LTerm = LTerm::make_atom(45);
pub const TL: LTerm = LTerm::make_atom(46);
pub const TRAP_EXIT: LTerm = LTerm::make_atom(47);
pub const TRUE: LTerm = LTerm::make_atom(48);
pub const UNDEF: LTerm = LTerm::make_atom(49);
pub const UNDEFINED: LTerm = LTerm::make_atom(50);

pub static ATOM_INIT_NAMES: &'static [&'static str] = &[
  "*", // id=0
  "+", // id=1
  "++", // id=2
  "-", // id=3
  "/=", // id=4
  "<", // id=5
  "=/=", // id=6
  "=:=", // id=7
  "=<", // id=8
  "==", // id=9
  ">", // id=10
  ">=", // id=11
  "apply", // id=12
  "atom_to_list", // id=13
  "badarg", // id=14
  "badarith", // id=15
  "badarity", // id=16
  "badfun", // id=17
  "badmatch", // id=18
  "case_clause", // id=19
  "erlang", // id=20
  "error", // id=21
  "exit", // id=22
  "false", // id=23
  "function_clause", // id=24
  "hd", // id=25
  "high", // id=26
  "if_clause", // id=27
  "init", // id=28
  "integer_to_list", // id=29
  "is_process_alive", // id=30
  "kill", // id=31
  "killed", // id=32
  "length", // id=33
  "lists", // id=34
  "low", // id=35
  "make_fun", // id=36
  "member", // id=37
  "nif_error", // id=38
  "nocatch", // id=39
  "normal", // id=40
  "ok", // id=41
  "self", // id=42
  "spawn", // id=43
  "system_limit", // id=44
  "throw", // id=45
  "tl", // id=46
  "trap_exit", // id=47
  "true", // id=48
  "undef", // id=49
  "undefined", // id=50
];
